Repository QUT-Motorsport/QUTMS_Driverless, pull requests merged in 2023-08, with the labels that each got.

#275 Particle pursuit, Planning nodes, OOP
  src/control/path_follower/path_follower/deprecated/node_particle_pursuit.py
  src/control/path_follower/path_follower/node_particle_pursuit_inherit.py
  src/control/path_follower/path_follower/node_pure_pursuit.py
  src/control/path_follower/setup.py
  src/navigation/planners/planners/deprecated/node_cone_interpolator.py
  src/navigation/planners/planners/deprecated/node_delaunay_planner.py
  src/navigation/planners/planners/deprecated/node_equidistant_midline.py
  src/navigation/planners/planners/deprecated/node_midline_planner.py
  src/navigation/planners/planners/deprecated/node_ordered_cones.py
  src/navigation/planners/planners/node_ordered_mid_spline.py
  src/navigation/planners/setup.py
  src/operations/mission_controller/launch/trackdrive.launch.py
Labels: Feature, Refactoring, Optimising

#276 Cli additions
  tools/qutms_cli_tools/qutms_cli_tools/build.py
  tools/qutms_cli_tools/qutms_cli_tools/common.py
  tools/qutms_cli_tools/qutms_cli_tools/format.py
  tools/qutms_cli_tools/qutms_cli_tools/launch.py
  tools/qutms_cli_tools/qutms_cli_tools/main.py
  tools/qutms_cli_tools/qutms_cli_tools/pull.py
  tools/qutms_cli_tools/qutms_cli_tools/record.py
Labels: Feature, Optimising

#279 State spoofing
  src/operations/terminal_control/setup.py
  src/operations/terminal_control/terminal_control/node_state_controller.py
  src/operations/terminal_control/terminal_control/node_state_gui.py
Labels: Feature
